//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreelancerModStudio.Properties {
    using System.Drawing;
    using System.Globalization;
    using System.Resources;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>

    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute(
        "System.Resources.Tools.StronglyTypedResourceBuilder",
        "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {
        private static ResourceManager resourceMan;

        private static CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute(
            "Microsoft.Performance",
            "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(
            global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    ResourceManager temp = new global::System.Resources.ResourceManager(
                        "FreelancerModStudio.Properties.Resources",
                        typeof(Resources).Assembly);
                    resourceMan = temp;
                }

                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(
            global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }

            set
            {
                resourceCulture = value;
            }
        }

        internal static Bitmap About
        {
            get
            {
                object obj = ResourceManager.GetObject("About", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static Bitmap Add
        {
            get
            {
                object obj = ResourceManager.GetObject("Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static Bitmap Close
        {
            get
            {
                object obj = ResourceManager.GetObject("Close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static Bitmap CloseMod
        {
            get
            {
                object obj = ResourceManager.GetObject("CloseMod", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static Bitmap Construct
        {
            get
            {
                object obj = ResourceManager.GetObject("Construct", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static Bitmap Copy
        {
            get
            {
                object obj = ResourceManager.GetObject("Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static Bitmap Cut
        {
            get
            {
                object obj = ResourceManager.GetObject("Cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1.0.0.0.
        /// </summary>
        internal static string DefaultModVersion
        {
            get
            {
                return ResourceManager.GetString("DefaultModVersion", resourceCulture);
            }
        }

        internal static Bitmap Delete
        {
            get
            {
                object obj = ResourceManager.GetObject("Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static Bitmap DeleteFolder
        {
            get
            {
                object obj = ResourceManager.GetObject("DeleteFolder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static Bitmap Depot
        {
            get
            {
                object obj = ResourceManager.GetObject("Depot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static Bitmap DockingRing
        {
            get
            {
                object obj = ResourceManager.GetObject("DockingRing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static Bitmap Document
        {
            get
            {
                object obj = ResourceManager.GetObject("Document", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static Icon Error
        {
            get
            {
                object obj = ResourceManager.GetObject("Error", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        internal static Bitmap File
        {
            get
            {
                object obj = ResourceManager.GetObject("File", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static Bitmap Filedll
        {
            get
            {
                object obj = ResourceManager.GetObject("Filedll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static Bitmap Fileini
        {
            get
            {
                object obj = ResourceManager.GetObject("Fileini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static Icon FileINIIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("FileINIIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        internal static Bitmap Filetxt
        {
            get
            {
                object obj = ResourceManager.GetObject("Filetxt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static Bitmap Filewav
        {
            get
            {
                object obj = ResourceManager.GetObject("Filewav", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static Bitmap Filter
        {
            get
            {
                object obj = ResourceManager.GetObject("Filter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static Bitmap Folder
        {
            get
            {
                object obj = ResourceManager.GetObject("Folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static Bitmap FullScreen
        {
            get
            {
                object obj = ResourceManager.GetObject("FullScreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static Bitmap GoTo
        {
            get
            {
                object obj = ResourceManager.GetObject("GoTo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static Bitmap HiddenFile
        {
            get
            {
                object obj = ResourceManager.GetObject("HiddenFile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static Bitmap HiddenFolder
        {
            get
            {
                object obj = ResourceManager.GetObject("HiddenFolder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static Bitmap HiddenFolderOpen
        {
            get
            {
                object obj = ResourceManager.GetObject("HiddenFolderOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static Bitmap HomePage
        {
            get
            {
                object obj = ResourceManager.GetObject("HomePage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static Bitmap JumpGate
        {
            get
            {
                object obj = ResourceManager.GetObject("JumpGate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static Bitmap JumpHole
        {
            get
            {
                object obj = ResourceManager.GetObject("JumpHole", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FreelancerModStudio.Layout.xml.
        /// </summary>
        internal static string LayoutPath
        {
            get
            {
                return ResourceManager.GetString("LayoutPath", resourceCulture);
            }
        }

        internal static Bitmap LightSource
        {
            get
            {
                object obj = ResourceManager.GetObject("LightSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static Bitmap LogoAbout
        {
            get
            {
                object obj = ResourceManager.GetObject("LogoAbout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static Icon LogoIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("LogoIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        internal static Bitmap Mod
        {
            get
            {
                object obj = ResourceManager.GetObject("Mod", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .flmsm.
        /// </summary>
        internal static string ModExtension
        {
            get
            {
                return ResourceManager.GetString("ModExtension", resourceCulture);
            }
        }

        internal static Bitmap NewDocument
        {
            get
            {
                object obj = ResourceManager.GetObject("NewDocument", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static Bitmap NewFolder
        {
            get
            {
                object obj = ResourceManager.GetObject("NewFolder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static Bitmap NewMod
        {
            get
            {
                object obj = ResourceManager.GetObject("NewMod", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static Bitmap NewWindow
        {
            get
            {
                object obj = ResourceManager.GetObject("NewWindow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static Icon Note
        {
            get
            {
                object obj = ResourceManager.GetObject("Note", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        internal static Bitmap Open
        {
            get
            {
                object obj = ResourceManager.GetObject("Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static Bitmap OpenFolder
        {
            get
            {
                object obj = ResourceManager.GetObject("OpenFolder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static Bitmap OpenMod
        {
            get
            {
                object obj = ResourceManager.GetObject("OpenMod", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static Bitmap Paste
        {
            get
            {
                object obj = ResourceManager.GetObject("Paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static Bitmap Planet
        {
            get
            {
                object obj = ResourceManager.GetObject("Planet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static Icon Properties
        {
            get
            {
                object obj = ResourceManager.GetObject("Properties", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        internal static Bitmap ReDo
        {
            get
            {
                object obj = ResourceManager.GetObject("ReDo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static Bitmap ReportIssue
        {
            get
            {
                object obj = ResourceManager.GetObject("ReportIssue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static Bitmap Satellite
        {
            get
            {
                object obj = ResourceManager.GetObject("Satellite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static Bitmap Save
        {
            get
            {
                object obj = ResourceManager.GetObject("Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static Bitmap SaveAll
        {
            get
            {
                object obj = ResourceManager.GetObject("SaveAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static Bitmap Settings
        {
            get
            {
                object obj = ResourceManager.GetObject("Settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FreelancerModStudio.xml.
        /// </summary>
        internal static string SettingsPath
        {
            get
            {
                return ResourceManager.GetString("SettingsPath", resourceCulture);
            }
        }

        internal static Bitmap Ship
        {
            get
            {
                object obj = ResourceManager.GetObject("Ship", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static Icon SolutionExplorer
        {
            get
            {
                object obj = ResourceManager.GetObject("SolutionExplorer", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        internal static Bitmap Station
        {
            get
            {
                object obj = ResourceManager.GetObject("Station", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static Bitmap Sun
        {
            get
            {
                object obj = ResourceManager.GetObject("Sun", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static Bitmap System
        {
            get
            {
                object obj = ResourceManager.GetObject("System", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Template.xml.
        /// </summary>
        internal static string TemplatePath
        {
            get
            {
                return ResourceManager.GetString("TemplatePath", resourceCulture);
            }
        }

        internal static Bitmap TradeLane
        {
            get
            {
                object obj = ResourceManager.GetObject("TradeLane", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static Bitmap UnDo
        {
            get
            {
                object obj = ResourceManager.GetObject("UnDo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string UpdateDownloadPath
        {
            get
            {
                return ResourceManager.GetString("UpdateDownloadPath", resourceCulture);
            }
        }

        internal static Bitmap UpFolder
        {
            get
            {
                object obj = ResourceManager.GetObject("UpFolder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static Bitmap WeaponsPlatform
        {
            get
            {
                object obj = ResourceManager.GetObject("WeaponsPlatform", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static Bitmap WebSearch
        {
            get
            {
                object obj = ResourceManager.GetObject("WebSearch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static Bitmap Zone
        {
            get
            {
                object obj = ResourceManager.GetObject("Zone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static Bitmap ZoneBox
        {
            get
            {
                object obj = ResourceManager.GetObject("ZoneBox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static Bitmap ZoneBoxExclusion
        {
            get
            {
                object obj = ResourceManager.GetObject("ZoneBoxExclusion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static Bitmap ZoneCylinder
        {
            get
            {
                object obj = ResourceManager.GetObject("ZoneCylinder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static Bitmap ZoneCylinderExclusion
        {
            get
            {
                object obj = ResourceManager.GetObject("ZoneCylinderExclusion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static Bitmap ZoneExclusion
        {
            get
            {
                object obj = ResourceManager.GetObject("ZoneExclusion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static Bitmap ZonePath
        {
            get
            {
                object obj = ResourceManager.GetObject("ZonePath", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static Bitmap ZonePathTrade
        {
            get
            {
                object obj = ResourceManager.GetObject("ZonePathTrade", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static Bitmap ZonePathTradeLane
        {
            get
            {
                object obj = ResourceManager.GetObject("ZonePathTradeLane", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static Bitmap ZoneVignette
        {
            get
            {
                object obj = ResourceManager.GetObject("ZoneVignette", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
