//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:2.0.50727.1433
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreelancerModStudio.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FreelancerModStudio.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About {0} ähnelt.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The current mod will be closed.
        ///
        ///Would you like to save changes to {0}? ähnelt.
        /// </summary>
        internal static string CloseSave {
            get {
                return ResourceManager.GetString("CloseSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} of {1} MB ähnelt.
        /// </summary>
        internal static string DownloadSpeed {
            get {
                return ResourceManager.GetString("DownloadSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The entered mod homepage is invalid. ähnelt.
        /// </summary>
        internal static string InvalidModHomepage {
            get {
                return ResourceManager.GetString("InvalidModHomepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The mod name must not contain the following chars: / ? : &amp; * &quot; &lt; &gt; | # %
        ///
        ///Please enter a valid name. ähnelt.
        /// </summary>
        internal static string InvalidModNameChars {
            get {
                return ResourceManager.GetString("InvalidModNameChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The mod path must not contain the following chars: / ? : &amp; * &quot; &lt; &gt; | # %
        ///
        ///Please enter a valid name. ähnelt.
        /// </summary>
        internal static string InvalidModPathChars {
            get {
                return ResourceManager.GetString("InvalidModPathChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The settings file &quot;{0}&quot; could not be loaded. ähnelt.
        /// </summary>
        internal static string LoadSettingsException {
            get {
                return ResourceManager.GetString("LoadSettingsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The template file &quot;{0}&quot; could not be loaded. ähnelt.
        /// </summary>
        internal static string LoadTemplateException {
            get {
                return ResourceManager.GetString("LoadTemplateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mod{0} ähnelt.
        /// </summary>
        internal static string NewModName {
            get {
                return ResourceManager.GetString("NewModName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The settings file &quot;{0}&quot; could not be saved. ähnelt.
        /// </summary>
        internal static string SaveSettingsException {
            get {
                return ResourceManager.GetString("SaveSettingsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Abort ähnelt.
        /// </summary>
        internal static string UpdatesAbortButton {
            get {
                return ResourceManager.GetString("UpdatesAbortButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There are new updates for {0} aviable. Do you want to download them now? ähnelt.
        /// </summary>
        internal static string UpdatesAviableDescription {
            get {
                return ResourceManager.GetString("UpdatesAviableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Updates Found ähnelt.
        /// </summary>
        internal static string UpdatesAviableHeader {
            get {
                return ResourceManager.GetString("UpdatesAviableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} is now checking for updates... ähnelt.
        /// </summary>
        internal static string UpdatesCheckingDescription {
            get {
                return ResourceManager.GetString("UpdatesCheckingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Checking for Updates ähnelt.
        /// </summary>
        internal static string UpdatesCheckingHeader {
            get {
                return ResourceManager.GetString("UpdatesCheckingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Download ähnelt.
        /// </summary>
        internal static string UpdatesDownloadButton {
            get {
                return ResourceManager.GetString("UpdatesDownloadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The updates were successfully downloaded. You have to restart {0} in order to install the updates. ähnelt.
        /// </summary>
        internal static string UpdatesDownloadedDescription {
            get {
                return ResourceManager.GetString("UpdatesDownloadedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download Complete ähnelt.
        /// </summary>
        internal static string UpdatesDownloadedHeader {
            get {
                return ResourceManager.GetString("UpdatesDownloadedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An Error occured while downloading. Please check your internet connection and make sure that your firewall does not block {0}.
        ///
        ///If that problem persists, download and install the update manually. ähnelt.
        /// </summary>
        internal static string UpdatesDownloadException {
            get {
                return ResourceManager.GetString("UpdatesDownloadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} is now downloading the new updates... ähnelt.
        /// </summary>
        internal static string UpdatesDownloadingDescription {
            get {
                return ResourceManager.GetString("UpdatesDownloadingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Downloading Updates ähnelt.
        /// </summary>
        internal static string UpdatesDownloadingHeader {
            get {
                return ResourceManager.GetString("UpdatesDownloadingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Finish ähnelt.
        /// </summary>
        internal static string UpdatesFinishButton {
            get {
                return ResourceManager.GetString("UpdatesFinishButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}% - Software Update ähnelt.
        /// </summary>
        internal static string UpdatesFormDownloadText {
            get {
                return ResourceManager.GetString("UpdatesFormDownloadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Software Update ähnelt.
        /// </summary>
        internal static string UpdatesFormText {
            get {
                return ResourceManager.GetString("UpdatesFormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Hide ähnelt.
        /// </summary>
        internal static string UpdatesHideButton {
            get {
                return ResourceManager.GetString("UpdatesHideButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Install ähnelt.
        /// </summary>
        internal static string UpdatesInstallButton {
            get {
                return ResourceManager.GetString("UpdatesInstallButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Later ähnelt.
        /// </summary>
        internal static string UpdatesLaterButton {
            get {
                return ResourceManager.GetString("UpdatesLaterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There are no new updates aviable. {0} may check periodically for new updates. ähnelt.
        /// </summary>
        internal static string UpdatesNotAviableDescription {
            get {
                return ResourceManager.GetString("UpdatesNotAviableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Updates Found ähnelt.
        /// </summary>
        internal static string UpdatesNotAviableHeader {
            get {
                return ResourceManager.GetString("UpdatesNotAviableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version {0} ähnelt.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
