//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5472
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreelancerModStudio.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FreelancerModStudio.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0}.
        /// </summary>
        internal static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string AboutVersion {
            get {
                return ResourceManager.GetString("AboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error List.
        /// </summary>
        internal static string ErrorListText {
            get {
                return ResourceManager.GetString("ErrorListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &apos;{0}&apos;?.
        /// </summary>
        internal static string FileCloseSave {
            get {
                return ResourceManager.GetString("FileCloseSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string FileDefaultCategory {
            get {
                return ResourceManager.GetString("FileDefaultCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INI-Files (*.ini)|*.ini|FLMM Backup INI-Files (*.ini.flmmbak)|*.ini.flmmbak.
        /// </summary>
        internal static string FileDialogFilter {
            get {
                return ResourceManager.GetString("FileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string FileEditorColumnName {
            get {
                return ResourceManager.GetString("FileEditorColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string FileEditorColumnType {
            get {
                return ResourceManager.GetString("FileEditorColumnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No entries existing....
        /// </summary>
        internal static string FileEditorEmpty {
            get {
                return ResourceManager.GetString("FileEditorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New File.
        /// </summary>
        internal static string FileEditorNewFile {
            get {
                return ResourceManager.GetString("FileEditorNewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Solar Archetype INI ({0}).
        /// </summary>
        internal static string FileEditorOpenSolarArch {
            get {
                return ResourceManager.GetString("FileEditorOpenSolarArch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save {0}.
        /// </summary>
        internal static string FileEditorSave {
            get {
                return ResourceManager.GetString("FileEditorSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save {0} &amp;as....
        /// </summary>
        internal static string FileEditorSaveAs {
            get {
                return ResourceManager.GetString("FileEditorSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; could not be opened..
        /// </summary>
        internal static string FileErrorOpen {
            get {
                return ResourceManager.GetString("FileErrorOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; cannot be opened. Do you want to remove it from the Recent list?.
        /// </summary>
        internal static string FileErrorOpenRecent {
            get {
                return ResourceManager.GetString("FileErrorOpenRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; could not be saved. Please check if it is opened in another application or if the file is marked as read-only..
        /// </summary>
        internal static string FileErrorSave {
            get {
                return ResourceManager.GetString("FileErrorSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered mod homepage is invalid..
        /// </summary>
        internal static string ModInvalidHomepage {
            get {
                return ResourceManager.GetString("ModInvalidHomepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mod name must not contain the following chars: / ? : &amp; * &quot; &lt; &gt; | # %
        ///
        ///Please enter a valid name..
        /// </summary>
        internal static string ModInvalidNameChars {
            get {
                return ResourceManager.GetString("ModInvalidNameChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mod path must not contain the following chars: / ? : &amp; * &quot; &lt; &gt; | # %
        ///
        ///Please enter a valid name..
        /// </summary>
        internal static string ModInvalidPathChars {
            get {
                return ResourceManager.GetString("ModInvalidPathChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod{0}.
        /// </summary>
        internal static string ModNewName {
            get {
                return ResourceManager.GetString("ModNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string PropertiesText {
            get {
                return ResourceManager.GetString("PropertiesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings file &apos;{0}&apos; could not be loaded..
        /// </summary>
        internal static string SettingsLoadException {
            get {
                return ResourceManager.GetString("SettingsLoadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings file &apos;{0}&apos; could not be saved..
        /// </summary>
        internal static string SettingsSaveException {
            get {
                return ResourceManager.GetString("SettingsSaveException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution Explorer.
        /// </summary>
        internal static string SolutionExplorerText {
            get {
                return ResourceManager.GetString("SolutionExplorerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open {0}....
        /// </summary>
        internal static string SystemPresenterOpen {
            get {
                return ResourceManager.GetString("SystemPresenterOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angles: .
        /// </summary>
        internal static string SystemPresenterTrackedAngles {
            get {
                return ResourceManager.GetString("SystemPresenterTrackedAngles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance: .
        /// </summary>
        internal static string SystemPresenterTrackedDistance {
            get {
                return ResourceManager.GetString("SystemPresenterTrackedDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The template file &apos;{0}&apos; could not be loaded..
        /// </summary>
        internal static string TemplateLoadException {
            get {
                return ResourceManager.GetString("TemplateLoadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Abort.
        /// </summary>
        internal static string UpdatesAbortButton {
            get {
                return ResourceManager.GetString("UpdatesAbortButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are new updates for {0} available. Do you want to download them now?.
        /// </summary>
        internal static string UpdatesAviableDescription {
            get {
                return ResourceManager.GetString("UpdatesAviableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Updates Found.
        /// </summary>
        internal static string UpdatesAviableHeader {
            get {
                return ResourceManager.GetString("UpdatesAviableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is now checking for updates....
        /// </summary>
        internal static string UpdatesCheckingDescription {
            get {
                return ResourceManager.GetString("UpdatesCheckingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for Updates.
        /// </summary>
        internal static string UpdatesCheckingHeader {
            get {
                return ResourceManager.GetString("UpdatesCheckingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Download.
        /// </summary>
        internal static string UpdatesDownloadButton {
            get {
                return ResourceManager.GetString("UpdatesDownloadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The updates were successfully downloaded. You have to restart {0} in order to install the updates..
        /// </summary>
        internal static string UpdatesDownloadedDescription {
            get {
                return ResourceManager.GetString("UpdatesDownloadedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Complete.
        /// </summary>
        internal static string UpdatesDownloadedHeader {
            get {
                return ResourceManager.GetString("UpdatesDownloadedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error occured while downloading. Please check your internet connection and make sure that your firewall does not block {0}.
        ///
        ///If that problem persists, download and install the update manually..
        /// </summary>
        internal static string UpdatesDownloadException {
            get {
                return ResourceManager.GetString("UpdatesDownloadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is now downloading the new updates....
        /// </summary>
        internal static string UpdatesDownloadingDescription {
            get {
                return ResourceManager.GetString("UpdatesDownloadingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Updates.
        /// </summary>
        internal static string UpdatesDownloadingHeader {
            get {
                return ResourceManager.GetString("UpdatesDownloadingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} MB.
        /// </summary>
        internal static string UpdatesDownloadSpeed {
            get {
                return ResourceManager.GetString("UpdatesDownloadSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Finish.
        /// </summary>
        internal static string UpdatesFinishButton {
            get {
                return ResourceManager.GetString("UpdatesFinishButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}% - Software Update.
        /// </summary>
        internal static string UpdatesFormDownloadText {
            get {
                return ResourceManager.GetString("UpdatesFormDownloadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Update.
        /// </summary>
        internal static string UpdatesFormText {
            get {
                return ResourceManager.GetString("UpdatesFormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Hide.
        /// </summary>
        internal static string UpdatesHideButton {
            get {
                return ResourceManager.GetString("UpdatesHideButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Install.
        /// </summary>
        internal static string UpdatesInstallButton {
            get {
                return ResourceManager.GetString("UpdatesInstallButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Later.
        /// </summary>
        internal static string UpdatesLaterButton {
            get {
                return ResourceManager.GetString("UpdatesLaterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no new updates available. {0} may check periodically for new updates..
        /// </summary>
        internal static string UpdatesNotAviableDescription {
            get {
                return ResourceManager.GetString("UpdatesNotAviableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Updates Found.
        /// </summary>
        internal static string UpdatesNotAviableHeader {
            get {
                return ResourceManager.GetString("UpdatesNotAviableHeader", resourceCulture);
            }
        }
    }
}
